export const icons = {
    IC_USER: require('../assets/icons/User.png'),
    IC_PASSWORD:require('../assets/icons/password.png'),
    IC_EMAIL:require('../assets/icons/ic_mail.png'),
    IC_GOOGLE:require('../assets/icons/google1.png'),
    IC_APPLE:require('../assets/icons/apple.png'),
    IC_FACEBOOK:require('../assets/icons/facebook1.png'),
    IC_EYE_OPEN:require('../assets/icons/eye_open1.png'),
    IC_EYE_CLOSE:require('../assets/icons/eye_close1.png'),
    IC_MIC_OFF:require('../assets/icons/mic1.png'),
    IC_MIC_ON:require('../assets/icons/mic2.png'),
    IC_SEARCH: require('../assets/icons/search1.png'),
    IC_BOTTOMMENU_HOMESELECT: require('../assets/icons/Bottom_Menu/home_select.png'),
    IC_BOTTOMMENU_HOMEUNSELECT: require('../assets/icons/Bottom_Menu/home_unselect.png'),
    IC_BOTTOMMENU_WISHLISTSELECT: require('../assets/icons/Bottom_Menu/wishlist_select.png'),
    IC_BOTTOMMENU_WISHLISTUNSELECT:  require('../assets/icons/Bottom_Menu/wishlist_unselect.png'),
    IC_BOTTOMMENU_CARTSELECT:  require('../assets/icons/Bottom_Menu/cart_select.png'),
    IC_BOTTOMMENU_CARTUNSELECT:  require('../assets/icons/Bottom_Menu/cart_unselect.png'),
    IC_BOTTOMMENU_SEARCHSELECT:  require('../assets/icons/Bottom_Menu/search_select.png'),
    IC_BOTTOMMENU_SEARCHUNSELECT:  require('../assets/icons/Bottom_Menu/search_unselect.png'),
    IC_BOTTOMMENU_SETTINGSELECT:  require('../assets/icons/Bottom_Menu/setting_select.png'),
    IC_BOTTOMMENU_SETTINGUNSELECT:  require('../assets/icons/Bottom_Menu/setting_unselect.png'),
    IC_RIGHT_ARROW: require("../assets/icons/right_arrow.png"),
    IC_CLOCK:require("../assets/icons/clock.png"),
    IC_STAR: require("../assets/icons/star.png"),
    IC_STAR_UNFILLED: require("../assets/icons/star_unfilled.png"),
    IC_CALENDER:require("../assets/icons/calender.png"),
    IC_APPLE_ARROW_RIGHT:require("../assets/icons/apple_arrow_right.png"),
    IC_MENU:require("../assets/icons/menu.png"),
  IC_ARROW_LEFT:require("../assets/icons/Toolbar/apple_arrow_left.png"),
  IC_CART: require("../assets/icons/Toolbar/carticn.png"),
  IC_NEARSTORE:require("../assets/icons/nearstore.png"),
  IC_VIP:require("../assets/icons/vip.png"),
  IC_RETURNPOLICY:require("../assets/icons/returnpolicy.png"),
  IC_COMPARE:require("../assets/icons/compare.png"),
  IC_EDIT:require("../assets/icons/edit.png"),
  IC_LOCATION:require("../assets/icons/location.png"),
  IC_EDITADDRESS:require("../assets/icons/editAddress.png"),
  IC_ADD_ADDRESS:require("../assets/icons/addAddress.png"),
  IC_FAVORITE:require("../assets/icons/favorite.png"),
  IC_COUPON:require("../assets/icons/coupen.png")
  };


  export const image = {
   ONBOARDING1:require('../assets/image/WT1.png'),
   ONBOARDING2:require('../assets/image/WT2.png'),
   ONBOARDING3:require('../assets/image/WT3.png'),
   LOGO1:require('../assets/image/logo.png'),
   LOGO2:require('../assets/image/logo2.png'),
   GETSTART:require('../assets/image/getstart.png'),
   SUCCESSFULL:require('../assets/image/sucessfull.png'),
   PROFILE: require('../assets/image/profile.png'),
   FEATURE1: require('../assets/image/feature1.png'),
   FEATURE2: require('../assets/image/feature2.png'),
   FEATURE3: require('../assets/image/feature3.png'),
   FEATURE4: require('../assets/image/feature4.png'),
   FEATURE5: require('../assets/image/feature5.png'),
   CAROUSALIMG: require('../assets/image/Carousal_img.png'),
   DOD_IMG1:require("../assets/image/DOD/image1.png"),
   DOD_IMG2:require("../assets/image/DOD/image2.png"),
   SPECIAL_OFFER:require("../assets/image/special_offer.png"),
   HEELS:require("../assets/image/heels.png"),
   WATCH1:require("../assets/image/Products/watch1.png"),
   SHOES1:require("../assets/image/Products/shoes1.png"),
   HANDBAG1:require("../assets/image/Products/handbag1.png"),
   SUMMERSALEBORDING:require("../assets/image/summersale.png"),
   SPONSERBOARDING:require("../assets/image/sponser.png"),
   TSHIRT1:require("../assets/image/Products/tshirt1.png"),
   SHIRT1:require("../assets/image/Products/shirt1.png"),
   SHOES2:require("../assets/image/Products/shoes2.png"),
   SHOES3:require("../assets/image/Products/shoes3.png"),
   SHOES4:require("../assets/image/shoes4.png"),
   SHOES5:require("../assets/image/shoes5.png"),
   SHOES6:require("../assets/image/shoes6.png"),
   DRESS1:require("../assets/image/Products/dress1.png"),
   DRESS2:require("../assets/image/Products/dress2.png"),
   DRESS3:require("../assets/image/Products/dress3.png"),
   DRESS4:require("../assets/image/Products/dress4.png"),
  MOBILE1:require("../assets/image/Products/mobile1.png"),
  PS5:require("../assets/image/Products/ps5.png"),
 JACKET1:require("../assets/image/Products/jacket1.png"),
  CAMERA:require("../assets/image/Products/camera.png"),
 PROTIEN:require("../assets/image/Products/protien.png"),
 HOTCHOCO:require("../assets/image/Products/hotchoco.png"),
 GOCARTBTN: require("../assets/image/gocart.png"),
 BUYNOWBTN: require("../assets/image/buynow.png"),
 VISA:require("../assets/image/visa.png"),
 PAYPAL:require("../assets/image/paypal.png"),
 MAESTRO:require("../assets/image/maestro.png"),
 APPLEPAY:require("../assets/image/applepay.png"),

  
   
  };





  